apiVersion: "openebs.io/v1beta1"
kind: DiskPool
metadata:
  name: dp-nc1
  namespace: mayastor
spec:
  node: nc1
  disks: ["/dev/disk/by-id/wwn-0x5002538d422741de"]
---
apiVersion: "openebs.io/v1beta1"
kind: DiskPool
metadata:
  name: dp-nc2
  namespace: mayastor
spec:
  node: nc2
  disks: ["/dev/disk/by-id/wwn-0x5002538d423ebab2"]
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-1
parameters:
  ioTimeout: "30"
  protocol: nvmf
  repl: "1"
provisioner: io.openebs.csi-mayastor
