# FROM: curl https://raw.githubusercontent.com/minio/docs/master/source/extra/examples/minio.yaml -O
# Deploys a new Namespace for the MinIO Pod
apiVersion: v1
kind: Namespace
metadata:
  name: minio # Change this value if you want a different namespace name
  labels:
    name: minio # Change this value to match metadata.name
---
# Deploys a new MinIO Pod into the metadata.namespace Kubernetes namespace
#
# The `spec.containers[0].args` contains the command run on the pod
# The `/data` directory corresponds to the `spec.containers[0].volumeMounts[0].mountPath`
# That mount path corresponds to a Kubernetes HostPath which binds `/data` to a local drive or volume on the worker node where the pod runs
# 
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
  namespace: minio # Change this value to match the namespace metadata.name
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio:latest
    command:
    - /bin/bash
    - -c
    args: 
    - minio server /data --console-address :9090
    volumeMounts:
    - mountPath: /data
      name: minio-vol # Corresponds to the `spec.volumes` Persistent Volume
    - mountPath: /root/.minio
      name: minio-config
    ports:
    - name: minio-con-port
      containerPort: 9090
    - name: minio-port
      containerPort: 9000
    env:
    - name: MINIO_ROOT_USER
      value: admin
    - name: MINIO_ROOT_PASSWORD
      value: changeme
      
  nodeSelector:
    kubernetes.io/hostname: nc2 # Specify a node label associated to the Worker Node on which you want to deploy the pod.
  volumes:
  - name: minio-vol
    hostPath: # MinIO generally recommends using locally-attached volumes
      path: /data/minio # Specify a path to a local drive or volume on the Kubernetes worker node
      type: DirectoryOrCreate # The path to the last directory must exist
  - name: minio-config
    hostPath: # MinIO generally recommends using locally-attached volumes
      path: /root/.minio # Specify a path to a local drive or volume on the Kubernetes worker node
      type: DirectoryOrCreate # The path to the last directory must exist
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: minio-console-port
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30099
    - name: minio-api-port
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30090